name: Lint Commit Messages using cocogitto
on:
  push:
    # release.yml workflow does it already there.
    branches-ignore:
      - main
      - gh-pages
  pull_request:
jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: fetch tags (see https://github.com/actions/checkout/issues/290)
        run: echo not needed? git fetch --tags --force || exit 0
      - name: show git details
        run: git describe --abbrev=0 || exit 0
      - name: show git details tags
        run: git describe --abbrev=0 --tags || exit 0
      - name: list git tags
        run: git tag -ln || exit 0

      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@v2
        with:
          git-user: 'mbehr1'
          git-user-email: 'mbehr+adlt@mcbehr.de'
          check-latest-tag-only: true
