name: Lint Commit Messages using cocogitto
on:
  push:
    # release.yml workflow does it already there.
    branches-ignore:
      - main
      - gh-pages
  pull_request:
jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@v2
        with:
          git-user: 'mbehr1'
          git-user-email: 'mbehr+adlt@mcbehr.de'
          check-latest-tag-only: true
